// Auto-generated Bridging Header for RedB
// This imports the C FFI functions generated by uniffi.
// The path to redb_coreFFI.h is resolved via SWIFT_INCLUDE_PATHS or User Header Search Paths.

#include "redb_coreFFI.h"
