import Foundation

let mySQLFunctions: [String] = [
    // ---- String Functions ----
    "ASCII", "BIN", "BIT_LENGTH", "CHAR", "CHAR_LENGTH", "CHARACTER_LENGTH",
    "CONCAT", "CONCAT_WS", "ELT", "EXPORT_SET", "FIELD", "FIND_IN_SET",
    "FORMAT", "FROM_BASE64", "HEX", "INSERT", "INSTR", "LCASE",
    "LEFT", "LENGTH", "LIKE", "LOAD_FILE", "LOCATE", "LOWER",
    "LPAD", "LTRIM", "MAKE_SET", "MATCH", "MID", "OCT",
    "OCTET_LENGTH", "ORD", "POSITION", "QUOTE", "REGEXP", "REGEXP_INSTR",
    "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR", "REPEAT", "REPLACE", "REVERSE",
    "RIGHT", "RPAD", "RTRIM", "SOUNDEX", "SPACE", "STRCMP",
    "SUBSTR", "SUBSTRING", "SUBSTRING_INDEX", "TO_BASE64", "TRIM", "UCASE",
    "UNHEX", "UPPER", "WEIGHT_STRING",

    // ---- Numeric / Math Functions ----
    "ABS", "ACOS", "ASIN", "ATAN", "ATAN2", "AVG",
    "CEIL", "CEILING", "COS", "COT", "COUNT", "DEGREES",
    "DIV", "EXP", "FLOOR", "GREATEST", "LEAST", "LN",
    "LOG", "LOG10", "LOG2", "MAX", "MIN", "MOD",
    "PI", "POW", "POWER", "RADIANS", "RAND", "ROUND",
    "SIGN", "SIN", "SQRT", "SUM", "TAN", "TRUNCATE",

    // ---- Date / Time Functions ----
    "ADDDATE", "ADDTIME", "CONVERT_TZ", "CURDATE", "CURRENT_DATE", "CURRENT_TIME",
    "CURRENT_TIMESTAMP", "CURTIME", "DATE", "DATE_ADD", "DATE_FORMAT", "DATE_SUB",
    "DATEDIFF", "DAY", "DAYNAME", "DAYOFMONTH", "DAYOFWEEK", "DAYOFYEAR",
    "EXTRACT", "FROM_DAYS", "FROM_UNIXTIME", "GET_FORMAT", "HOUR", "LAST_DAY",
    "LOCALTIME", "LOCALTIMESTAMP", "MAKEDATE", "MAKETIME", "MICROSECOND", "MINUTE",
    "MONTH", "MONTHNAME", "NOW", "PERIOD_ADD", "PERIOD_DIFF", "QUARTER",
    "SEC_TO_TIME", "SECOND", "STR_TO_DATE", "SUBDATE", "SUBTIME", "SYSDATE",
    "TIME", "TIME_FORMAT", "TIME_TO_SEC", "TIMEDIFF", "TIMESTAMP", "TIMESTAMPADD",
    "TIMESTAMPDIFF", "TO_DAYS", "TO_SECONDS", "UNIX_TIMESTAMP", "UTC_DATE", "UTC_TIME",
    "UTC_TIMESTAMP", "WEEK", "WEEKDAY", "WEEKOFYEAR", "YEAR", "YEARWEEK",

    // ---- Control Flow Functions ----
    "CASE", "COALESCE", "IF", "IFNULL", "NULLIF",

    // ---- Aggregation / Window Functions ----
    "AVG", "BIT_AND", "BIT_OR", "BIT_XOR", "COUNT", "GROUP_CONCAT",
    "JSON_ARRAYAGG", "JSON_OBJECTAGG", "MAX", "MIN", "STD", "STDDEV",
    "STDDEV_POP", "STDDEV_SAMP", "SUM", "VAR_POP", "VAR_SAMP", "VARIANCE",
    "CUME_DIST", "DENSE_RANK", "FIRST_VALUE", "LAG", "LAST_VALUE", "LEAD",
    "NTH_VALUE", "NTILE", "PERCENT_RANK", "RANK", "ROW_NUMBER",

    // ---- Cast / Conversion ----
    "BINARY", "CAST", "CONVERT", "DECODE", "ENCODE",

    // ---- Encryption / Hash ----
    "AES_DECRYPT", "AES_ENCRYPT", "MD5", "RANDOM_BYTES", "SHA1", "SHA2",
    "SHA", "UNCOMPRESS", "UNCOMPRESSED_LENGTH",

    // ---- JSON Functions ----
    "JSON_ARRAY", "JSON_ARRAY_APPEND", "JSON_ARRAY_INSERT", "JSON_CONTAINS",
    "JSON_CONTAINS_PATH", "JSON_DEPTH", "JSON_EXTRACT", "JSON_INSERT",
    "JSON_KEYS", "JSON_LENGTH", "JSON_MERGE", "JSON_MERGE_PATCH",
    "JSON_MERGE_PRESERVE", "JSON_OBJECT", "JSON_OVERLAPS", "JSON_PRETTY",
    "JSON_QUOTE", "JSON_REMOVE", "JSON_REPLACE", "JSON_SCHEMA_VALID",
    "JSON_SCHEMA_VALIDATION_REPORT", "JSON_SEARCH", "JSON_SET", "JSON_STORAGE_FREE",
    "JSON_STORAGE_SIZE", "JSON_TABLE", "JSON_TYPE", "JSON_UNQUOTE",
    "JSON_VALID", "JSON_VALUE", "MEMBER OF",

    // ---- Information Functions ----
    "BENCHMARK", "CHARSET", "COERCIBILITY", "COLLATION", "CONNECTION_ID",
    "CURRENT_ROLE", "CURRENT_USER", "DATABASE", "FOUND_ROWS", "ICU_VERSION",
    "LAST_INSERT_ID", "ROW_COUNT", "SCHEMA", "SESSION_USER", "SYSTEM_USER",
    "USER", "VERSION",

    // ---- Misc ----
    "ANY_VALUE", "DEFAULT", "GROUPING", "INET_ATON", "INET_NTOA", "INET6_ATON",
    "INET6_NTOA", "IS_IPV4", "IS_IPV4_COMPAT", "IS_IPV4_MAPPED", "IS_IPV6",
    "ISNULL", "MASTER_POS_WAIT", "NAME_CONST", "SLEEP", "UUID", "UUID_SHORT",
    "VALUES",
]

/// All available keywords for highlighting & completion.
let sqlKeywords: Set<String> = [
    "SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "IN", "IS", "NULL",
    "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE", "CREATE",
    "TABLE", "DROP", "ALTER", "ADD", "COLUMN", "INDEX", "PRIMARY",
    "KEY", "FOREIGN", "REFERENCES", "CONSTRAINT", "DEFAULT", "UNIQUE",
    "JOIN", "LEFT", "RIGHT", "INNER", "OUTER", "ON", "AS", "ORDER",
    "BY", "GROUP", "HAVING", "LIMIT", "OFFSET", "UNION", "ALL", "DISTINCT",
    "CASE", "WHEN", "THEN", "ELSE", "END", "EXISTS", "BETWEEN", "LIKE",
    "COUNT", "SUM", "AVG", "MIN", "MAX", "CAST", "COALESCE", "NULLIF",
    "TRUE", "FALSE", "IF", "REPLACE", "TRUNCATE", "DESCRIBE", "SHOW",
    "USE", "DATABASE", "SCHEMA", "GRANT", "REVOKE", "COMMIT", "ROLLBACK",
    "BEGIN", "TRANSACTION", "EXPLAIN", "ANALYZE", "WITH", "RECURSIVE",
    "ASC", "DESC", "CROSS", "NATURAL", "USING", "ANY", "SOME",
]
